repos:
- repo: https://github.com/ambv/black
  rev: 18.6b4
  hooks:
  - id: black
    language_version: python3.6
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
  - id: flake8
    additional_dependencies: ["flake8-bugbear==18.2.0"]
- repo: https://github.com/asottile/blacken-docs
  rev: v0.2.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==18.6b4]
