language: python
sudo: false
cache:
  pip: true
  directories:
  - "$HOME/.cache"
env:
  global:
  - ELASTICSEARCH_ARCHIVE=elasticsearch-6.3.1.tar.gz
  - ELASTICSEARCH_HOST=127.0.0.1:9200
install:
- travis_retry pip install -U tox
script: tox
before_install:
- 'mkdir -p $HOME/.cache/downloads

'
- |
  cd $HOME/.cache/downloads

  if [ ! -f "$ELASTICSEARCH_ARCHIVE" ]; then
    curl -SLO https://artifacts.elastic.co/downloads/elasticsearch/$ELASTICSEARCH_ARCHIVE
  fi

  if [ ! -f "$ELASTICSEARCH_ARCHIVE.sha1.txt" ]; then
    curl -SLO https://artifacts.elastic.co/downloads/elasticsearch/$ELASTICSEARCH_ARCHIVE.sha512
  fi

  sha512sum --check $ELASTICSEARCH_ARCHIVE.sha1.txt

  mkdir -p /tmp/elasticsearch
  tar xzf $ELASTICSEARCH_ARCHIVE -C /tmp/elasticsearch --strip-components=1
- "/tmp/elasticsearch/bin/elasticsearch > /dev/null & export ELASTICSEARCH_PID=$!"
- |-
  while true; do
      sleep 5
      curl -sf http://localhost:9200/_cluster/health?wait_for_status=yellow
      if [ $? -eq 0 ]; then
          break
      fi
  done
- cd $TRAVIS_BUILD_DIR
before_cache:
- kill -9 $ELASTICSEARCH_PID

jobs:
  fast_finish: true
  include:
  - { python: '3.6', env: TOXENV=lint, before_install: skip, before_cache: skip }
  - { python: '2.7', env: TOXENV=py27-django111 }
  - { python: '3.6', env: TOXENV=py36-django111 }
  - { python: '3.6', env: TOXENV=py36-django20 }
  - { python: '3.6', env: TOXENV=py36-django111 }
  - { python: '3.6', env: TOXENV=py36-django20 }

  - stage: PyPI Release
    if: tag IS present
    python: "3.6"
    env: []
    # Override before_install, install, and script to no-ops
    before_install: skip
    install: skip
    script: skip
    before_cache: skip
    deploy:
      provider: pypi
      user: cos
      password:
        secure: AEBvufx5x0RcSrQpK1uNQRgXtPnBqub/d2pkwSTf+pFABnoGxdcf0qUsXgt6I3EGGxhkkxJ+tTvJzkz2Qt0x5GE83Mh6Jn6fVlGxQIAQx5rvE0AZId2cy/+uIbcaftkaYmpXkPAMZCP5POvGiziRvEecO9YHF4OizfmDLJ+ZnmxRgMW2eCPX5isONT50E3kuztgmvClqNVdJ54XnbJ3vDD7yx0Qx1NsfTWkRGod/d2og9tx4iOM+aOmQC5ayozBkepUHyBL4Qxo1ZHccxr5zg5YYysy7QKPoBh4j/l59x7Pg0K4laBfKmDZG1tG7kBoe/H+yG+M1LWXNCYEt359QXXOA9gs/PTX7HljMEleUxboUY3uV/FgZKU63qp9UG+AjiVzBVSlH/f5o088pX54pHYnBXizoq7+EVEBuiVEzs7TiS5uqbeyDqlRnGvdG7tePorXSN3+4rAwsrSjdgP9mxRt4OkTXPy7xodSzZSosZ5rfACuChiDFFTs5ZwQS3k2MPkz14+NyTWXTIkdbsETbiHgcnW8KKHag1hES99ocI3rojilPaYm6W7XQ8TjclQ3YclhFv5dtRHlJt6MnozAyrtcCP6mSlQn1w1YlkQ2UMk+QgQGPylC4Mxkz8/bXYojSdDYe8QFANu6gyf2WqbvCUoOF/+tlJkBZ7KvNIEwy8RM=
      on:
        tags: true
      distributions: sdist bdist_wheel
