version: '3'
services:
  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    environment:
      discovery.type: single-node
  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    environment:
      discovery.type: single-node
  elasticsearch8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    environment:
      discovery.type: single-node
      ELASTIC_CLIENT_APIVERSIONING: 1  # act like es7
      xpack.security.enabled: "false"
      action.destructive_requires_name: "false"
  testbox:
    build:
      context: .
      dockerfile: testbox.Dockerfile
    depends_on:
      # - elasticsearch6
      # - elasticsearch7
      - elasticsearch8
    environment:
      # ELASTICSEARCH_HOST: elasticsearch6:9200
      # ELASTICSEARCH_HOST: elasticsearch7:9200
      ELASTICSEARCH_HOST: elasticsearch8:9200
    volumes:
      - ./:/code:cached
