version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
  testbox:
    build:
      context: .
      dockerfile: testbox.Dockerfile
    depends_on:
      - elasticsearch
    environment:
      TOXENV: py39-django40
      ELASTICSEARCH_HOST: elasticsearch:9200
    volumes:
      - ./:/code:cached
