version: '3'
services:
  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    healthcheck:
      interval: 30s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    networks:
      - djelme
  elasticsearch8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.11
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m  # reduce memory usage
    healthcheck:
      interval: 30s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    networks:
      - djelme
  testbox:
    build:
      context: .
      dockerfile: testbox.Containerfile
    depends_on:
      elasticsearch6:
        condition: service_healthy
      elasticsearch8:
        condition: service_healthy
    environment:
      # TOXENV: py310-django42
      ELASTICSEARCH6_URL: elasticsearch6:9200
      ELASTICSEARCH8_URL: http://elasticsearch8:9200
    networks:
      - djelme
    # volumes:
    #   - ./:/code:cached


networks:
  djelme:
    driver: bridge

