[tox]
envlist =
    lint
    py{310,311,312,313,314}-django{42,51,52}

[testenv]
passenv =
    ELASTICSEARCH6_URL
    ELASTICSEARCH8_URL
setenv =
    DJANGO_SETTINGS_MODULE={env:DJANGO_SETTINGS_MODULE:elasticsearch_metrics.tests.settings}
extras =
    elastic6
    elastic8
dependency_groups =
    tests
deps =
    django42: Django>=4.2,<5.0
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<6.0
commands =
    poetry run python3 -m elasticsearch_metrics.tests --test {posargs}
allowlist_externals =
    poetry

[testenv:lint]
dependency_groups =
    lint
commands =
    poetry run python3 -m elasticsearch_metrics.tests --lint {posargs}
allowlist_externals =
    poetry
