name: test_djelme

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.7-slim
    steps:
      - uses: actions/checkout@v3
      - run: pip install tox
      - run: TOXENV=lint tox


  test:
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10']
        django: ['1.11', '2.0', '2.1', '2.2', '3.0', '3.1', '3.2', '4.0', '4.1']
        elastic: ['6', '7', '8']
        exclude:
          - {python: '3.7', django: '4.0'}
          - {python: '3.7', django: '4.1'}
          - {python: '3.10', django: '1.11'}
          - {python: '3.10', django: '2.0'}
    runs-on: ubuntu-latest
    container: python:${{matrix.python}}-slim
    services:
      elasticsearch6:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
        env:
          discovery.type: single-node
      elasticsearch7:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
        env:
          discovery.type: single-node
      elasticsearch8:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
        env:
          discovery.type: single-node
          ELASTIC_CLIENT_APIVERSIONING: 1            # act like es7
          xpack.security.enabled: "false"            # it'll be fine
          action.destructive_requires_name: "false"  # we'll delete * in a moment
    env:
      ELASTICSEARCH_HOST: elasticsearch${{matrix.elastic}}:9200
    steps:
      - uses: actions/checkout@v3
      - run: pip install -U tox
      - run: TOXENV=`echo 'py${{matrix.python}}-django${{matrix.django}}-es${{matrix.elastic}}' | sed 's/\.//g'` tox

