name: test_djelme

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        id: setup-py
        with:
          python-version: '3.13'
      - run: pip install poetry
      - run: poetry install --no-root --with=lint
      - run: poetry run python -m elasticsearch_metrics.tests --lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12', '3.13', '3.14']
        django: ['4.2', '5.1', '5.2']
    services:
      elasticsearch6:
        image: elasticsearch:6.8.23
        ports:
          - 9206:9200
      elasticsearch8:
        image: elasticsearch:8.19.11
        ports:
          - 9208:9200
        env:
          xpack.security.enabled: false
          node.name: singlenode
          cluster.initial_master_nodes: singlenode
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        id: setup-py
        with:
          python-version: ${{ matrix.python }}

      - name: alias python
        run: alias python${{ steps.setup-py.outputs.python-version }}=${{ steps.setup-py.outputs.python-path }}

      - name: install despondencies
        run: pip install -U poetry && poetry install --with=dev --extras=elastic6 --extras=elastic8

      - run: TOXENV=`echo 'py${{ matrix.python }}-django${{matrix.django}}' | sed 's/\.//g'` poetry run tox
        env:
          ELASTICSEARCH6_URL: http://localhost:9206
          ELASTICSEARCH8_URL: http://localhost:9208
